title: Giogioanni Capstone
description: CS499 Computer Science Capstone 2026
theme: minima

index.md
code-review.md
self-assessment.md

artifacts/
  appointment-service.md

enhancements/
  software-design.md
  algorithms-ds.md
  databases.md
