title: Giogioanni Capstone
description: CS499 Computer Science Capstone 2026
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme

index.md
code-review.md
self-assessment.md

artifacts/
appointment-service.md

enhancements/
software-design.md
algorithms-ds.md
databases.md
